# fly.toml app configuration file generated for vidzly-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vidzly-backend"
primary_region = "fra" # Frankfurt, Germany - based on previous logs

[build]
  # No specific builder needed if Fly.io auto-detects Node.js correctly.

[env]
  PORT = "3001" # Make sure your app listens on this port

# Corrected from [[http_service]] to [http_service]
[http_service]
  internal_port = 3001 # The port your Node.js app (server.js) listens on
  force_https = true
  auto_stop_machines = true # Stop machines when idle (good for free tier)
  auto_start_machines = true # Start machines on demand
  min_machines_running = 0 # Allow machines to scale to zero

  [[http_service.checks]] # This is an array of tables, correct
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/healthz" # Your server.js has a /healthz endpoint
    port = 3001 # Health check must target the internal_port
    protocol = "http" # Health check is internal, HTTP is fine
    grace_period = "5s" # Give app time to start before first check

  [[http_service.ports]] # This is an array of tables, correct
    handlers = ["http"]
    port = 80

  [[http_service.ports]] # This is an array of tables, correct
    handlers = ["tls", "http"] # TLS termination is handled by Fly.io's proxy
    port = 443

# VM configuration based on your previous `flyctl launch` output
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024